Adds a string conversion for algorithms and some formatting
notaryproject/notation-core-go pull request #111
Opened 2023-02-01 20:24 UTC by byronchien

String conversion for algorithm enum used for inspect. Other changes result from `gofmt`

Signed-off-by: Byron Chien <chienb@amazon.com>

2023-02-02 19:50 UTC, byronchien commented
required for notation inspect (added in this PR: https://github.com/notaryproject/notation/pull/528)

2023-02-02 19:51 UTC, priteshbandi commented
Looks like there are couple of files with white space changes, can we drop those files from this PR?

2023-02-03 06:07 UTC, patrickzheng200 commented on signature/algorithm.go
> +	}[alg]
Looks like the elements in this string array have to strictly follow the order defined in `const`.  
I've seen an alternative implementation from [go-cose](https://github.com/veraison/go-cose/blob/07c7d28e2c7eb9d6daa4619b98eceeaf7a8e5156/algorithm.go#L52). Using switch statements seems easier to maintain.

2023-02-07 00:30 UTC, shizhMSFT requested changes
We don't have a spec on the standard string of those algorithms. AFAIK, those strings come from the plugin spec. Therefore, those changes should be in the `notation-go` repo.

2023-02-07 00:44 UTC, byronchien commented
> We don't have a spec on the standard string of those algorithms. AFAIK, those strings come from the plugin spec. Therefore, those changes should be in the `notation-go` repo.

ok, if [this helper](https://github.com/notaryproject/notation-go/blob/61ffb0982848f62509497eda9e0088c90368d7ff/plugin/proto/algorithm.go#L132) doesn't work, will add to notation-go instead. will verify before closing this PR

2023-02-08 18:07 UTC, byronchien commented
used the existing EncodeSigningAlgorithm helper, resolving

2023-02-08 18:07 UTC, closed without merging